name: Build and Release AlbionBlackLedger

on:
  push:
    tags:
      - 'v*'  # Trigger workflow on version tags like
permissions:
  contents: write
  
jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: ğŸ“¥ Checkout code
      uses: actions/checkout@v3

    - name: ğŸ Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.13'

    - name: ğŸ“¦ Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pyinstaller
        pip install -r requirements.txt

    - name: Download items.json
      run: |
        curl -L -o items.json https://raw.githubusercontent.com/ao-data/ao-bin-dumps/refs/heads/master/formatted/items.json

    - name: Run item parser
      run: python items_parser.py
    
    - name: ğŸ”§ Build EXE with PyInstaller
      run: |
        pyinstaller --onefile --windowed main.py `
          --add-data "item_map.json;." `
          --add-data "blackledger.ico;." `
          --icon=blackledger.ico `
          --name AlbionBlackLedger

    - name: ğŸšš Move EXE to root
      run: |
        $version = "${env:GITHUB_REF}".Split("/")[-1]
        move dist\\AlbionBlackLedger.exe AlbionBlackLedger-$version.exe

    - name: ğŸš€ Create GitHub Release
      uses: softprops/action-gh-release@v2
      with:
        name: AlbionBlackLedger ${{ github.ref_name }}
        tag_name: ${{ github.ref_name }}
        files: AlbionBlackLedger.exe
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
